import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  MainContainer: {
    justifyContent: 'center',
    flex: 1,
  },
  listPadding: {padding: 16},
  seperator: {
    height: 10,
    width: '100%',
  },
  footer: {
    height: 60,
    width: '100%',
  },
  cartView: {
    backgroundColor: '#fff',
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#404040',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  cartTouch: {
    backgroundColor: '#fb641b',
    width: 120,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartText: {fontSize: 16, color: '#fff'},
  shopNow: {
    backgroundColor: '#0065FF',
    width: 120,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
  },
  priceCardOuterView: {
    backgroundColor: '#FFF',
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 50,
  },
  priceDetailsText: {margin: 14},
  line: {height: 1, backgroundColor: '#E2e2e2'},
  totalAmountContainer: {
    flexDirection: 'row',
    margin: 14,
    marginTop: 12,
    marginBottom: 12,
    justifyContent: 'space-between',
  },
  deliveryFeeValue: {color: 'green'},
  deliveryFeeContainer: {
    flexDirection: 'row',
    margin: 14,
    marginTop: 12,
    marginBottom: 16,
    justifyContent: 'space-between',
  },
  price: {
    flexDirection: 'row',
    margin: 14,
    marginBottom: 0,
    justifyContent: 'space-between',
  },
  footerPrice: {fontSize: 18, color: '#0065FF', fontWeight: '500'},
  emptyView: {flex: 1, backgroundColor: '#FFF', alignItems: 'center'},
  empty: {height: '20%', width: '100%'},
  emptyTitle: {fontSize: 20, fontWeight: '500', marginTop: 50},
  emptyDesc: {fontSize: 14, marginTop: 14},
  successOuter: {flex: 1, backgroundColor: '#FFF', alignItems: 'center'},
  successImg: {height: 160, width: 160},
  successText: {
    fontSize: 20,
    fontWeight: '500',
    marginTop: 50,
    textAlign: 'center',
  },
  successDesc: {fontSize: 14, marginTop: 14},
});
